#!/bin/bash
# A script to automate the process of making API requests to the Pokémon API and saving the results to a file

# 1. Save the response in a variable (capture error too 2>&1 otherwise it goes to the termianl)
# 2. Check if the status the last executed command (curl) is an error (!= 0)
# 3. Store the errors in errors.txt and output in data.json

response=$(curl -s https://pokeapi.co/api/v2/pokemon/25/ 2>&1)
if [ $? -ne 0 ]; then  # Error
	echo "$response" > errors.txt
else
	echo "$response" > data.json
fi
