#!/bin/bash
# A script to automate the retrieval of data for multiple Pokémon and store it in separate files

mkdir -p pokemon_data

for name in Bulbasaur Ivysaur Venusaur Charmander Charmeleon; do
	echo "Fetching data for $name..."
	curl -s "https://pokeapi.co/api/v2/pokemon/$name" > "pokemon_data/$name.json"
	echo "Saved data to pokemon_data/$name.json ✅"
	sleep 1  # Hanlde rate-limiting
done
