#!/bin/bash
# Script that fetches data by using parallel processing & leveraging background processes

mkdir -p new_pokemon_data

pokemon_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

for name in "${pokemon_list[@]}"; do
	echo "Fetching data for $name..."
	# Run curl in the background
	curl -s -f "https://pokeapi.co/api/v2/pokemon/$name" > "new_pokemon_data/$name.json" &
done

# Wait for all background processes to finish
wait

echo "All downloads finished ✅"
