#!/bin/bash
# A script to automate the retrieval of data for multiple Pokémon and store it in separate files

mkdir -p pokemon_data

# Bash array of Pokémon names
pokemon_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

# Loop over the array
for name in "${pokemon_list[@]}"; do
	echo "Fetching data for $name..."
	curl -s "https://pokeapi.co/api/v2/pokemon/$name" > "pokemon_data/$name.json"
	echo "Saved data to pokemon_data/$name.json ✅"
	sleep 1  # Hanlde rate-limiting
done
