#!/bin/bash
# A script that reads all the JSON files & extracts the name, height, and weight from each file

# Add the header to the csv file
echo "Name,Height (m),Weight (kg)" > pokemon_report.csv

pokemon_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

# Sort the array alphabetically
IFS=$'\n' sorted_list=($(sort <<<"${pokemon_list[*]}"))
unset IFS

for name in "${sorted_list[@]}"; do
	p_name=$(jq -r '.name' "pokemon_data/$name.json")

	# Capitalize the first letter
	p_name=$(echo "$p_name" | sed 's/^\(.\)/\U\1/')
	height=$(jq -r '.height' "pokemon_data/$name.json" | awk '{printf "%.1f", $1/10}')
	weight=$(jq -r '.weight' "pokemon_data/$name.json" | awk '{printf "%.1f", $1/10}')
	
	# Append the values to the csv file
	echo "$p_name,$height,$weight" >> pokemon_report.csv
done

# Calculate the average weight and height from the data in the csv ignoring the first 3 lines (header)
avg_height=$(awk -F, 'NR>1 {sum+=$2; count++} END {print sum/count}' pokemon_report.csv)
avg_weight=$(awk -F, 'NR>1 {sum+=$3; count++} END {print sum/count}' pokemon_report.csv)


echo "CSV Report generated at: pokemon_report.csv"
echo ""

cat pokemon_report.csv

echo ""
echo "Average Height: $avg_height m"
echo "Average Weight: $avg_weight kg"
